spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/davidgh86/microservices-openshift
          search-paths:
            - "ms-config-properties/{application}/{profile}"